# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2deb9d2f4f301ff1bf0b7a33dfb69a6582f6d6338258799fac89ce024d8daee52b174b4aeecee4607c193c631a489a40adc35f264c570bbeee9d4dd73d3d51ed

test:
  secret_key_base: 75dd271ccaa2faae6dd9c3abb271136d6e950ed30614aa9a79813de0f4bdcdc3da1c03c0d416f5524270eb8554b79a2e2afecc906a9c1afb234d326f945e9825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
